import { Restaurant } from "@/app/restaurants/page";

export const RESTAURANTS: Restaurant[] = [
  {
    id: 1,
    name: "The Gourmet Bistro",
    description: "A cozy spot serving classic French cuisine.",
    address: "123 Main Street, San Francisco, CA",
    zipcode: "94117",
    cuisine: "French",
    priceRange: "$$$",
    ratings: 4.8,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 2,
    name: "Sushi Paradise",
    description: "Authentic sushi and sashimi made by expert chefs.",
    address: "456 Elm Street, San Francisco, CA",
    zipcode: "94105",
    cuisine: "Japanese",
    priceRange: "$$$",
    ratings: 4.5,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 3,
    name: "Pasta House",
    description: "A delightful Italian restaurant specializing in pasta dishes.",
    address: "789 Oak Avenue, San Francisco, CA",
    zipcode: "94112",
    cuisine: "Italian",
    priceRange: "$$",
    ratings: 4.3,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 4,
    name: "BBQ Nation",
    description: "The best BBQ ribs and smoked meats in town.",
    address: "101 Maple Lane, San Francisco, CA",
    zipcode: "94110",
    cuisine: "American",
    priceRange: "$$$",
    ratings: 4.7,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 5,
    name: "Curry Delight",
    description: "Spicy and flavorful Indian curries and naan.",
    address: "202 Pine Drive, San Francisco, CA",
    zipcode: "94106",
    cuisine: "Indian",
    priceRange: "$$",
    ratings: 4.6,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 6,
    name: "Taco Fiesta",
    description: "Authentic Mexican tacos and margaritas.",
    address: "303 Birch Street, San Francisco, CA",
    zipcode: "94103",
    cuisine: "Mexican",
    priceRange: "$",
    ratings: 4.2,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 7,
    name: "Dragon Wok",
    description: "Delicious Chinese food with a modern twist.",
    address: "404 Cherry Blvd, San Francisco, CA",
    zipcode: "94109",
    cuisine: "Chinese",
    priceRange: "$$",
    ratings: 4.5,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 8,
    name: "Green Leaf",
    description: "A vegan paradise with fresh and organic ingredients.",
    address: "505 Cedar Way, San Francisco, CA",
    zipcode: "94101",
    cuisine: "Vegan",
    priceRange: "$$",
    ratings: 4.6,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 9,
    name: "Pizza Planet",
    description: "Freshly baked pizzas with a variety of toppings.",
    address: "606 Spruce Road, San Francisco, CA",
    zipcode: "94115",
    cuisine: "Italian",
    priceRange: "$$",
    ratings: 4.3,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 10,
    name: "Steakhouse Supreme",
    description: "Premium steaks and fine wines.",
    address: "707 Willow Street, San Francisco, CA",
    zipcode: "94118",
    cuisine: "American",
    priceRange: "$$$$",
    ratings: 4.9,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 11,
    name: "Ocean Breeze",
    description: "Seafood delicacies with a coastal vibe.",
    address: "808 Bay Lane, San Francisco, CA",
    zipcode: "94114",
    cuisine: "Seafood",
    priceRange: "$$$",
    ratings: 4.6,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 12,
    name: "Mediterranean Magic",
    description: "Healthy and flavorful Mediterranean dishes.",
    address: "909 Palm Court, San Francisco, CA",
    zipcode: "94104",
    cuisine: "Mediterranean",
    priceRange: "$$",
    ratings: 4.4,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 13,
    name: "Burger Joint",
    description: "Classic burgers and fries with gourmet options.",
    address: "111 Main Plaza, San Francisco, CA",
    zipcode: "94102",
    cuisine: "American",
    priceRange: "$",
    ratings: 4.2,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 14,
    name: "Thai Spice",
    description: "Traditional Thai dishes with bold flavors.",
    address: "212 Broadway, San Francisco, CA",
    zipcode: "94119",
    cuisine: "Thai",
    priceRange: "$$",
    ratings: 4.5,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 15,
    name: "Bakery Bliss",
    description: "Freshly baked bread, pastries, and cakes.",
    address: "313 Sunset Blvd, San Francisco, CA",
    zipcode: "94111",
    cuisine: "Bakery",
    priceRange: "$",
    ratings: 4.7,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 16,
    name: "Fusion Feast",
    description: "Creative fusion cuisine blending global flavors.",
    address: "414 East Lane, San Francisco, CA",
    zipcode: "94108",
    cuisine: "Fusion",
    priceRange: "$$$",
    ratings: 4.8,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 17,
    name: "Breakfast Haven",
    description: "All-day breakfast classics with a twist.",
    address: "515 North Road, San Francisco, CA",
    zipcode: "94113",
    cuisine: "Breakfast",
    priceRange: "$$",
    ratings: 4.3,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 18,
    name: "Dim Sum Delight",
    description: "Traditional dim sum served fresh and hot.",
    address: "616 South Court, San Francisco, CA",
    zipcode: "94120",
    cuisine: "Chinese",
    priceRange: "$$",
    ratings: 4.4,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 19,
    name: "Grill & Chill",
    description: "Casual eatery with grilled specialties.",
    address: "717 West Boulevard, San Francisco, CA",
    zipcode: "94116",
    cuisine: "Barbecue",
    priceRange: "$",
    ratings: 4.1,
    imageUrl: "https://via.placeholder.com/150",
  },
  {
    id: 20,
    name: "Sweet Treats",
    description: "Desserts and ice creams to satisfy your sweet tooth.",
    address: "818 Park Avenue, San Francisco, CA",
    zipcode: "94107",
    cuisine: "Desserts",
    priceRange: "$",
    ratings: 4.6,
    imageUrl: "https://via.placeholder.com/150",
  },
];
